apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: easyclaim-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easyclaim-frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50