def COLOR_MAP = ['SUCCESS': 'good', 'FAILURE': 'danger', 'UNSTABLE': 'danger', 'ABORTED': 'danger']

pipeline {
    agent any
    environment {
        DATE = new Date().format('yy.M')
        TAG = "${DATE}.${BUILD_NUMBER}"
    }
    stages {
        stage('Build') {
            steps {
	            sh 'sudo npm install'
                sh 'sudo npm run build'
            }
        }
        stage('Docker Build') {
            steps {
               sh ' sudo docker build -t test . '
            }
        }
	    stage('Pushing Docker Image to Dockerhub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_credential') {
                        docker.image("vigneshsweekaran/easyclaim-frontend:${TAG}").push()
                        docker.image("vigneshsweekaran/easyclaim-frontend:${TAG}").push("32011")
                    }
                }
            }
        }
    }
}
