---
- name: Create pods using deployment 
  hosts: master
  tasks:
  - name: copy deployment file
    copy: src="./frontend-deployment.yml" dest="frontend-deployment.yml"

  - name: create a deployment
    command: kubectl apply -f frontend-deployment.yml
 
  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/easyclaim-frontend -n capstone
